server:
  port: 8085

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vanshsaini01/shirt-manufacturing-system
          default-label: main
